config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :categories do
    #collection do
    #  post "search"
    #end
    resources :products
  end


  root 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products , :dependent => :destroy

  #def self.search(search)
  #  where("name like ?", "%#{search}%")
  #end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  def self.search(category, search)
    if category.blank?
      where("name like ?", "%#{search}%")
    else
      where("category_id = ? and name like ?", category, "%#{search}%")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def ebay_category
    if Category.all.empty?
      url ="http://www.ebay.in/cat/mobiles"
      doc = Nokogiri::HTML(open(url))
      name = doc.css("#brand .nav-tabs-m a")
      name.each do |category_name|
        name = Nokogiri::HTML(category_name.content).text
        if Category.find_by_name(name).nil?
          Category.create(:name => name)
        end
      end
    end
  end

  def ebay_product
    if Product.all.empty?
      product_descriptions = Array.new
      #buy_product_urls = Array.new
      Category.all.each do |cat|
        url = "http://www.ebay.in/cat/mobiles/brand/#{cat.name}"
        doc = Nokogiri::HTML(open(url))
        doc.css("#cpProductModuleItems").each do |item|
          name = item.css("#itemsdiv a")
          name.each do |link|
            product_descriptions_url = "http://www.ebay.in#{link['href']}"
            #buy_product_urls.push(product_descriptions_url)
            product_description = Nokogiri::HTML(open(product_descriptions_url)).css(".row-fluid~ .row-fluid+ span .span12").text
            product_description = product_description.gsub("\r\n\t\t\t\t\t","")
            product_descriptions.push(product_description)
          end
          image = item.css("#itemsdiv img")
          name =  item.css("#itemsdiv div.itemtitle p a")
          #name = name.split("...")
          price = item.css("#itemsdiv .discount").text
          price = price.split("Rs. ")
          name.each_with_index do |product_name,i|
            product_image = image[i]['src']
            product_price =  price[i+1].gsub(",","").to_i
            @category = Category.find_by_name(cat.name)
            @category.products.create(:image => product_image, :name => product_name['title'],:price => product_price,
                                      :description => product_descriptions[i+1],:buy_product => product_name['href'])
          end
        end
      end
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  require 'open-uri'
  before_action :ebay_category
  before_action :ebay_product

  def index
    @categories = Category.all
  end

  def show
    @category_products = @category.products
    @category_products = @category_products.page(params[:page]).per_page(5)

    if params[:search]
      @categories = @category_products.search(params[:search])
    else
      @categories = Category.all
    end
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @category = Category.find(params[:id])
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  require 'open-uri'

  def index
    #@products = Product.all
    if params[:search]
      @products = Product.search(params[:category_id],params[:search])
    else
      @products = Product.all
    end
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
     respond_to do |format|
      if @product.save
        format.html { redirect_to category_path(@product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :price, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>CATEGORY LISTS</h1>
<table>
  <thead>
  <tr>
    <th>S.NO</th>
    <th>Name</th>
    <th>&nbsp;</th>
  </tr>
  </thead>
  <tbody>
  <% @categories.each_with_index do |category,index| %>
  <tr>
      <td><%= index+1 %></td>
      <td><%= link_to category.name,category_path(category) %></div></td>
      <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
  </tr>
  </tbody>
</table>
<br>
<%#= link_to 'New Category', new_category_path %>
<%= link_to 'Product Path', products_path%>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  Category name : <strong><%= @category.name %></strong>
</p>
<table>
  <thead>
  <tr>
    <th>Product Image</th>
    <th>Product Name</th>
    <th>price(in INR)</th>
  </tr>
  </thead>
  <tbody>
  <% @category_products.each do |product| %>
      <tr>
        <td><%= image_tag (product.image),:style => "width:100px;height:90px" %></td>
        <td><%= link_to product.name, product_path(product) %></td>
        <td><%=product.price %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'Back', categories_path %></br>
<p><%= will_paginate @category_products %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NokogiriApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<tr><%= form_tag products_path, :method => 'get' do %>
      <p>
        <%= select_tag :category_id, options_for_select([["Catagory Name",nil]] +Category.all.collect {|category| [category.name, category.id]}){} %>
        <%= text_field_tag :search,params[:search],placeholder: "Search Products"%>
        <%= submit_tag "search",:name => nil %>
      </p>
  <% end %>
</tr>
<%= yield %>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
    <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
            <% @product.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :price %><br>
      <%= f.text_field :price %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container">
  <h3><b>Listing Products</b></h3>

  <% @products.each do |product| %>
      <div class="flistingblock ">
        <div class="imgListingContainer">
          <%= image_tag (product.image) %>
        </div>
        <div class="browseImg imgContainerShadow"></div>
        <div class="itemtitle">
          <%=link_to product.name, product %>
        </div>
        <div>
          <span class="price">Starts @ </span>
          <%= product.price %>
        </div>
      </div>
  <% end %>
</div>
<h5><b><%= link_to 'Category List', categories_path %></b></h5>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Product name</strong>
  <%= @product.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%#= link_to 'Edit', edit_product_path(@product) %> 
<%= link_to 'Back', :back %>  |
<%= link_to 'category Page', categories_path %>
<%=link_to "<button>Buy Products</button>".html_safe, "http://www.ebay.in/#{@product.buy_product}" %>